/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-08-09 11:48:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>LocalConnect - Find Services Near You</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            transition: background-color 0.3s, color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .dark-mode {\r\n");
      out.write("            background-color: #121212;\r\n");
      out.write("            color: #e0e0e0;\r\n");
      out.write("        }\r\n");
      out.write("        .category-card {\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .category-card:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-light px-4 py-2\">\r\n");
      out.write("    <a class=\"navbar-brand fw-bold\" href=\"#\">LocalConnect</a>\r\n");
      out.write("    <div class=\"ms-auto d-flex align-items-center\">\r\n");
      out.write("        <button class=\"btn btn-outline-dark me-2\" onclick=\"toggleTheme()\">\r\n");
      out.write("            <i class=\"bi bi-moon-fill\"></i> Theme\r\n");
      out.write("        </button>\r\n");
      out.write("        <a href=\"login.jsp\" class=\"btn btn-outline-primary me-2\">Login</a>\r\n");
      out.write("        <a href=\"register.jsp\" class=\"btn btn-primary\">Register</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<header class=\"text-center py-5 bg-primary text-white\">\r\n");
      out.write("    <h1 class=\"display-4 fw-bold\">Find Trusted Services Near You</h1>\r\n");
      out.write("    <p class=\"lead\">Connecting you with verified professionals in your area</p>\r\n");
      out.write("    <a href=\"explore-services.jsp\" class=\"btn btn-light btn-lg mt-3\">Explore Services</a>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<section class=\"container my-5\">\r\n");
      out.write("    <h2 class=\"mb-4 text-center\">Popular Categories</h2>\r\n");
      out.write("    <div class=\"row g-4\">\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("            <div class=\"card category-card shadow text-center p-3\">\r\n");
      out.write("                <i class=\"bi bi-tools fs-1\"></i>\r\n");
      out.write("                <h5 class=\"mt-2\">Electrician</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("            <div class=\"card category-card shadow text-center p-3\">\r\n");
      out.write("                <i class=\"bi bi-droplet-half fs-1\"></i>\r\n");
      out.write("                <h5 class=\"mt-2\">Plumber</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("            <div class=\"card category-card shadow text-center p-3\">\r\n");
      out.write("                <i class=\"bi bi-house-door fs-1\"></i>\r\n");
      out.write("                <h5 class=\"mt-2\">Home Cleaning</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("            <div class=\"card category-card shadow text-center p-3\">\r\n");
      out.write("                <i class=\"bi bi-scissors fs-1\"></i>\r\n");
      out.write("                <h5 class=\"mt-2\">Beautician</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section class=\"bg-light py-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2 class=\"text-center mb-4\">What Our Users Say</h2>\r\n");
      out.write("        <div class=\"row g-4\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card p-3 shadow\">\r\n");
      out.write("                    <p>\"Quick and reliable services. Found a great electrician within minutes!\"</p>\r\n");
      out.write("                    <h6 class=\"fw-bold\">- Priya R.</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card p-3 shadow\">\r\n");
      out.write("                    <p>\"Loved the UI, and the service quality was amazing! Highly recommended.\"</p>\r\n");
      out.write("                    <h6 class=\"fw-bold\">- Rakesh M.</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card p-3 shadow\">\r\n");
      out.write("                    <p>\"Finally, a platform that actually works for local service needs.\"</p>\r\n");
      out.write("                    <h6 class=\"fw-bold\">- Anita S.</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"text-center py-4 bg-dark text-white\">\r\n");
      out.write("    &copy; 2025 LocalConnect. All rights reserved.\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function toggleTheme() {\r\n");
      out.write("        document.body.classList.toggle(\"dark-mode\");\r\n");
      out.write("        localStorage.setItem(\"theme\", document.body.classList.contains(\"dark-mode\") ? \"dark\" : \"light\");\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Auto theme detection\r\n");
      out.write("    window.onload = function () {\r\n");
      out.write("        const theme = localStorage.getItem(\"theme\");\r\n");
      out.write("        const prefersDark = window.matchMedia(\"(prefers-color-scheme: dark)\").matches;\r\n");
      out.write("        if (theme === \"dark\" || (!theme && prefersDark)) {\r\n");
      out.write("            document.body.classList.add(\"dark-mode\");\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
