/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-08-11 12:20:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.localconnect.dto.UserDto;

public final class user_002ddashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.localconnect.dto.UserDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

UserDto user = (UserDto) session.getAttribute("user");
if (user == null || !"user".equals(user.getRole())) {
response.sendRedirect("login.jsp");
return;
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" xmlns:jsp=\"http://www.w3.org/1999/XSL/Transform\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>User Dashboard</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <style>\r\n");
      out.write("        .service-card {\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 20px 15px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0,0,0,0.1);\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("        .service-card:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(0,0,0,0.15);\r\n");
      out.write("        }\r\n");
      out.write("        .service-img {\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            height: 70px;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            align-self: center;\r\n");
      out.write("        }\r\n");
      out.write("        /* Background colors */\r\n");
      out.write("        .bg-cleaning { background-color: #2196f3; }\r\n");
      out.write("        .bg-plumbing { background-color: #ff9800; }\r\n");
      out.write("        .bg-electrician { background-color: #4caf50; }\r\n");
      out.write("        .bg-painting { background-color: #9c27b0; }\r\n");
      out.write("\r\n");
      out.write("        /* Progress bar */\r\n");
      out.write("         .carousel-progress {\r\n");
      out.write("             height: 4px;\r\n");
      out.write("             background-color: rgba(255, 255, 255, 0.2); /* light background under progress */\r\n");
      out.write("         }\r\n");
      out.write("        .carousel-progress-bar {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background-color: #ff9800; /* orange fill */\r\n");
      out.write("            width: 0%;\r\n");
      out.write("            transition: width linear;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Suggestions dropdown */\r\n");
      out.write("        #suggestions {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 100%;        /* Position right below input */\r\n");
      out.write("    left: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-top: none;\r\n");
      out.write("    max-height: 150px;\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("    background: white;\r\n");
      out.write("    z-index: 1000;\r\n");
      out.write("    display: none;\r\n");
      out.write("    box-shadow: 0 4px 6px rgba(0,0,0,0.1);\r\n");
      out.write("    border-radius: 0 0 10px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("        #suggestions div {\r\n");
      out.write("            padding: 8px 12px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("        }\r\n");
      out.write("        #suggestions div:hover, #suggestions div.highlight {\r\n");
      out.write("            background-color: #d6d6d6;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-white shadow-sm\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand fw-bold text-primary\" href=\"user-dashboard.jsp\">\r\n");
      out.write("            LocalConnect\r\n");
      out.write("        </a>\r\n");
      out.write("\r\n");
      out.write("        <!-- Mobile toggle -->\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarMenu\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarMenu\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Search Bar -->\r\n");
      out.write("            <form class=\"d-flex mx-auto\" action=\"search-services.jsp\" method=\"get\" style=\"max-width: 500px; flex: 1; position: relative;\">\r\n");
      out.write("                <input class=\"form-control me-2 rounded-pill shadow-sm\"\r\n");
      out.write("                       id=\"serviceSearch\"\r\n");
      out.write("                       type=\"search\"\r\n");
      out.write("                       name=\"search\"\r\n");
      out.write("                       placeholder=\"Search for services, categories...\"\r\n");
      out.write("                       aria-label=\"Search\"\r\n");
      out.write("                       autocomplete=\"off\"\r\n");
      out.write("                       required />\r\n");
      out.write("                <div id=\"suggestions\"></div>\r\n");
      out.write("                <button class=\"btn btn-primary rounded-pill px-4 shadow-sm\" type=\"submit\">Search</button>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <!-- Right Side Menu -->\r\n");
      out.write("            <ul class=\"navbar-nav ms-auto align-items-center\">\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"edit-user-profile.jsp\">Edit Profile</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"my-bookings.jsp\">My Bookings</a></li>\r\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"logout.jsp\">Logout</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Welcome Text -->\r\n");
      out.write("    <div class=\"mb-4 text-center\">\r\n");
      out.write("        <h2>Welcome, ");
      out.print( user.getName() );
      out.write("!</h2>\r\n");
      out.write("        <p class=\"lead text-muted\">Find the services you need quickly and easily.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Service Categories Grid -->\r\n");
      out.write("    <div class=\"row row-cols-2 row-cols-md-4 g-4 mb-5\">\r\n");
      out.write("        <div class=\"col\">\r\n");
      out.write("            <div class=\"service-card bg-cleaning\" onclick=\"location.href='search-services.jsp?category=Cleaning'\">\r\n");
      out.write("                <img src=\"images/clean.png\" alt=\"Cleaning\" class=\"service-img\" />\r\n");
      out.write("                <h5>Cleaning</h5>\r\n");
      out.write("                <p>Home & Office</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col\">\r\n");
      out.write("            <div class=\"service-card bg-plumbing\" onclick=\"location.href='search-services.jsp?category=Plumbing'\">\r\n");
      out.write("                <img src=\"images/plumb.png\" alt=\"Plumbing\" class=\"service-img\" />\r\n");
      out.write("                <h5>Plumbing</h5>\r\n");
      out.write("                <p>Fix leaks & pipes</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col\">\r\n");
      out.write("            <div class=\"service-card bg-electrician\" onclick=\"location.href='search-services.jsp?category=Electrician'\">\r\n");
      out.write("                <img src=\"images/electric.png\" alt=\"Electrician\" class=\"service-img\" />\r\n");
      out.write("                <h5>Electrician</h5>\r\n");
      out.write("                <p>Wiring & Repairs</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col\">\r\n");
      out.write("            <div class=\"service-card bg-painting\" onclick=\"location.href='search-services.jsp?category=Painting'\">\r\n");
      out.write("                <img src=\"images/paint.png\" alt=\"Painting\" class=\"service-img\" />\r\n");
      out.write("                <h5>Painting</h5>\r\n");
      out.write("                <p>Interior & Exterior</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Sliding Banner Carousel -->\r\n");
      out.write("    <div id=\"promoCarousel\" class=\"carousel slide rounded shadow overflow-hidden\"\r\n");
      out.write("         data-bs-ride=\"carousel\"\r\n");
      out.write("         data-bs-interval=\"3000\"\r\n");
      out.write("         data-bs-wrap=\"true\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"carousel-inner position-relative\">\r\n");
      out.write("            <div class=\"carousel-item active\">\r\n");
      out.write("                <img src=\"images/local.png\" class=\"d-block w-100\" alt=\"Promo 1\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"images/LookingForMehndiArtists.png\" class=\"d-block w-100\" alt=\"Promo 2\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"images/support2.png\" class=\"d-block w-100\" alt=\"Promo 3\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"images/gardan.png\" class=\"d-block w-100\" alt=\"Promo 4\">\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Progress bar inside box -->\r\n");
      out.write("            <div class=\"carousel-progress position-absolute bottom-0 start-0 w-100\">\r\n");
      out.write("                <div class=\"carousel-progress-bar\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery for autocomplete -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(function() {\r\n");
      out.write("        const $input = $('#serviceSearch');\r\n");
      out.write("        const $suggestions = $('#suggestions');\r\n");
      out.write("        let selectedIndex = -1;  // track keyboard selection\r\n");
      out.write("\r\n");
      out.write("        function renderSuggestions(data) {\r\n");
      out.write("            $suggestions.empty();\r\n");
      out.write("\r\n");
      out.write("            if (!Array.isArray(data) || data.length === 0) {\r\n");
      out.write("                $suggestions.hide();\r\n");
      out.write("                selectedIndex = -1;\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            data.forEach(function(service, index) {\r\n");
      out.write("                const name = service.serviceName || service.service_name || service.name || \"Unnamed\";\r\n");
      out.write("                const $item = $('<div></div>').text(name).appendTo($suggestions);\r\n");
      out.write("\r\n");
      out.write("                $item.on('click', function() {\r\n");
      out.write("                    $input.val(name);\r\n");
      out.write("                    $suggestions.empty().hide();\r\n");
      out.write("                    selectedIndex = -1;\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                $item.on('mouseenter', function() {\r\n");
      out.write("                    selectedIndex = index;\r\n");
      out.write("                    $suggestions.children().removeClass('highlight');\r\n");
      out.write("                    $(this).addClass('highlight');\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            selectedIndex = -1;\r\n");
      out.write("            $suggestions.show();\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $input.on('input', function() {\r\n");
      out.write("            const query = $(this).val().trim();\r\n");
      out.write("            if (query.length < 2) {\r\n");
      out.write("                $suggestions.empty().hide();\r\n");
      out.write("                selectedIndex = -1;\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: 'search-services',\r\n");
      out.write("                data: { q: query },\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                    renderSuggestions(data);\r\n");
      out.write("                },\r\n");
      out.write("                error: function() {\r\n");
      out.write("                    $suggestions.empty().hide();\r\n");
      out.write("                    selectedIndex = -1;\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $input.on('keydown', function(e) {\r\n");
      out.write("            const items = $suggestions.children();\r\n");
      out.write("            if (!$suggestions.is(':visible') || items.length === 0) return;\r\n");
      out.write("\r\n");
      out.write("            if (e.key === \"ArrowDown\") {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                selectedIndex = (selectedIndex + 1) % items.length;\r\n");
      out.write("                items.removeClass('highlight');\r\n");
      out.write("                $(items[selectedIndex]).addClass('highlight');\r\n");
      out.write("            } else if (e.key === \"ArrowUp\") {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                selectedIndex = (selectedIndex - 1 + items.length) % items.length;\r\n");
      out.write("                items.removeClass('highlight');\r\n");
      out.write("                $(items[selectedIndex]).addClass('highlight');\r\n");
      out.write("            } else if (e.key === \"Enter\") {\r\n");
      out.write("                if (selectedIndex >= 0) {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    const selectedText = $(items[selectedIndex]).text();\r\n");
      out.write("                    $input.val(selectedText);\r\n");
      out.write("                    $suggestions.empty().hide();\r\n");
      out.write("                    selectedIndex = -1;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(document).on('click', function(e) {\r\n");
      out.write("            if (!$(e.target).closest('#serviceSearch, #suggestions').length) {\r\n");
      out.write("                $suggestions.empty().hide();\r\n");
      out.write("                selectedIndex = -1;\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
